//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.PsdkInterfaces
{
    [Serializable]
    public class EscDataMsg : Message
    {
        public const string k_RosMessageName = "psdk_interfaces/EscData";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public EscStatusIndividualMsg[] esc;
        //  Array of ESC status

        public EscDataMsg()
        {
            this.header = new Std.HeaderMsg();
            this.esc = new EscStatusIndividualMsg[0];
        }

        public EscDataMsg(Std.HeaderMsg header, EscStatusIndividualMsg[] esc)
        {
            this.header = header;
            this.esc = esc;
        }

        public static EscDataMsg Deserialize(MessageDeserializer deserializer) => new EscDataMsg(deserializer);

        private EscDataMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.esc, EscStatusIndividualMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.esc);
            serializer.Write(this.esc);
        }

        public override string ToString()
        {
            return "EscDataMsg: " +
            "\nheader: " + header.ToString() +
            "\nesc: " + System.String.Join(", ", esc.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
