//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.PsdkInterfaces
{
    [Serializable]
    public class FileAttributesMsg : Message
    {
        public const string k_RosMessageName = "psdk_interfaces/FileAttributes";
        public override string RosMessageName => k_RosMessageName;

        public uint photo_ratio;
        public uint photo_rotation;
        public uint video_duration;
        public uint video_frame_rate;
        public uint video_rotation;
        public uint video_resolution;

        public FileAttributesMsg()
        {
            this.photo_ratio = 0;
            this.photo_rotation = 0;
            this.video_duration = 0;
            this.video_frame_rate = 0;
            this.video_rotation = 0;
            this.video_resolution = 0;
        }

        public FileAttributesMsg(uint photo_ratio, uint photo_rotation, uint video_duration, uint video_frame_rate, uint video_rotation, uint video_resolution)
        {
            this.photo_ratio = photo_ratio;
            this.photo_rotation = photo_rotation;
            this.video_duration = video_duration;
            this.video_frame_rate = video_frame_rate;
            this.video_rotation = video_rotation;
            this.video_resolution = video_resolution;
        }

        public static FileAttributesMsg Deserialize(MessageDeserializer deserializer) => new FileAttributesMsg(deserializer);

        private FileAttributesMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.photo_ratio);
            deserializer.Read(out this.photo_rotation);
            deserializer.Read(out this.video_duration);
            deserializer.Read(out this.video_frame_rate);
            deserializer.Read(out this.video_rotation);
            deserializer.Read(out this.video_resolution);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.photo_ratio);
            serializer.Write(this.photo_rotation);
            serializer.Write(this.video_duration);
            serializer.Write(this.video_frame_rate);
            serializer.Write(this.video_rotation);
            serializer.Write(this.video_resolution);
        }

        public override string ToString()
        {
            return "FileAttributesMsg: " +
            "\nphoto_ratio: " + photo_ratio.ToString() +
            "\nphoto_rotation: " + photo_rotation.ToString() +
            "\nvideo_duration: " + video_duration.ToString() +
            "\nvideo_frame_rate: " + video_frame_rate.ToString() +
            "\nvideo_rotation: " + video_rotation.ToString() +
            "\nvideo_resolution: " + video_resolution.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
