//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.PsdkInterfaces
{
    [Serializable]
    public class FileInfoMsg : Message
    {
        public const string k_RosMessageName = "psdk_interfaces/FileInfo";
        public override string RosMessageName => k_RosMessageName;

        public string name;
        public byte type;
        public uint size;
        public uint index;
        public long create_time_unix;
        public FileAttributesMsg attributes;
        public byte number_sub_files;
        public SubFileInfoMsg[] sub_files;

        public FileInfoMsg()
        {
            this.name = "";
            this.type = 0;
            this.size = 0;
            this.index = 0;
            this.create_time_unix = 0;
            this.attributes = new FileAttributesMsg();
            this.number_sub_files = 0;
            this.sub_files = new SubFileInfoMsg[0];
        }

        public FileInfoMsg(string name, byte type, uint size, uint index, long create_time_unix, FileAttributesMsg attributes, byte number_sub_files, SubFileInfoMsg[] sub_files)
        {
            this.name = name;
            this.type = type;
            this.size = size;
            this.index = index;
            this.create_time_unix = create_time_unix;
            this.attributes = attributes;
            this.number_sub_files = number_sub_files;
            this.sub_files = sub_files;
        }

        public static FileInfoMsg Deserialize(MessageDeserializer deserializer) => new FileInfoMsg(deserializer);

        private FileInfoMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.name);
            deserializer.Read(out this.type);
            deserializer.Read(out this.size);
            deserializer.Read(out this.index);
            deserializer.Read(out this.create_time_unix);
            this.attributes = FileAttributesMsg.Deserialize(deserializer);
            deserializer.Read(out this.number_sub_files);
            deserializer.Read(out this.sub_files, SubFileInfoMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.name);
            serializer.Write(this.type);
            serializer.Write(this.size);
            serializer.Write(this.index);
            serializer.Write(this.create_time_unix);
            serializer.Write(this.attributes);
            serializer.Write(this.number_sub_files);
            serializer.WriteLength(this.sub_files);
            serializer.Write(this.sub_files);
        }

        public override string ToString()
        {
            return "FileInfoMsg: " +
            "\nname: " + name.ToString() +
            "\ntype: " + type.ToString() +
            "\nsize: " + size.ToString() +
            "\nindex: " + index.ToString() +
            "\ncreate_time_unix: " + create_time_unix.ToString() +
            "\nattributes: " + attributes.ToString() +
            "\nnumber_sub_files: " + number_sub_files.ToString() +
            "\nsub_files: " + System.String.Join(", ", sub_files.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
