//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.PsdkInterfaces
{
    [Serializable]
    public class FlightStatusMsg : Message
    {
        public const string k_RosMessageName = "psdk_interfaces/FlightStatus";
        public override string RosMessageName => k_RosMessageName;

        public const byte FLIGHT_STATUS_STOPED = 0;
        public const byte FLIGHT_STATUS_ON_GROUND = 1;
        public const byte FLIGHT_STATUS_ON_AIR = 2;
        public Std.HeaderMsg header;
        public byte flight_status;

        public FlightStatusMsg()
        {
            this.header = new Std.HeaderMsg();
            this.flight_status = 0;
        }

        public FlightStatusMsg(Std.HeaderMsg header, byte flight_status)
        {
            this.header = header;
            this.flight_status = flight_status;
        }

        public static FlightStatusMsg Deserialize(MessageDeserializer deserializer) => new FlightStatusMsg(deserializer);

        private FlightStatusMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.flight_status);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.flight_status);
        }

        public override string ToString()
        {
            return "FlightStatusMsg: " +
            "\nheader: " + header.ToString() +
            "\nflight_status: " + flight_status.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
