//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.PsdkInterfaces
{
    [Serializable]
    public class HmsInfoTableMsg : Message
    {
        public const string k_RosMessageName = "psdk_interfaces/HmsInfoTable";
        public override string RosMessageName => k_RosMessageName;

        public uint num_msg;
        //  Length of 'table' array
        public HmsInfoMsgMsg[] table;
        //  Array of HmsInfoMsg

        public HmsInfoTableMsg()
        {
            this.num_msg = 0;
            this.table = new HmsInfoMsgMsg[0];
        }

        public HmsInfoTableMsg(uint num_msg, HmsInfoMsgMsg[] table)
        {
            this.num_msg = num_msg;
            this.table = table;
        }

        public static HmsInfoTableMsg Deserialize(MessageDeserializer deserializer) => new HmsInfoTableMsg(deserializer);

        private HmsInfoTableMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.num_msg);
            deserializer.Read(out this.table, HmsInfoMsgMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.num_msg);
            serializer.WriteLength(this.table);
            serializer.Write(this.table);
        }

        public override string ToString()
        {
            return "HmsInfoTableMsg: " +
            "\nnum_msg: " + num_msg.ToString() +
            "\ntable: " + System.String.Join(", ", table.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
