//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.PsdkInterfaces
{
    [Serializable]
    public class HmsInfoMsgMsg : Message
    {
        public const string k_RosMessageName = "psdk_interfaces/HmsInfoMsg";
        public override string RosMessageName => k_RosMessageName;

        public uint error_code;
        //  Error code associated to HMS message
        public byte component_index;
        //  Related to "payloadId" in the camera module
        public byte error_level;
        public string ground_info;
        //  Description of the error code if/when the drone is on the ground
        public string fly_info;
        //  Description of the error code if/when the drone is in the air
        public const byte MIN_HMS_ERROR_LEVEL = 0;
        public const byte MID_HMS_ERROR_LEVEL = 3;
        public const byte MAX_HMS_ERROR_LEVEL = 6;

        public HmsInfoMsgMsg()
        {
            this.error_code = 0;
            this.component_index = 0;
            this.error_level = 0;
            this.ground_info = "";
            this.fly_info = "";
        }

        public HmsInfoMsgMsg(uint error_code, byte component_index, byte error_level, string ground_info, string fly_info)
        {
            this.error_code = error_code;
            this.component_index = component_index;
            this.error_level = error_level;
            this.ground_info = ground_info;
            this.fly_info = fly_info;
        }

        public static HmsInfoMsgMsg Deserialize(MessageDeserializer deserializer) => new HmsInfoMsgMsg(deserializer);

        private HmsInfoMsgMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.error_code);
            deserializer.Read(out this.component_index);
            deserializer.Read(out this.error_level);
            deserializer.Read(out this.ground_info);
            deserializer.Read(out this.fly_info);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.error_code);
            serializer.Write(this.component_index);
            serializer.Write(this.error_level);
            serializer.Write(this.ground_info);
            serializer.Write(this.fly_info);
        }

        public override string ToString()
        {
            return "HmsInfoMsgMsg: " +
            "\nerror_code: " + error_code.ToString() +
            "\ncomponent_index: " + component_index.ToString() +
            "\nerror_level: " + error_level.ToString() +
            "\nground_info: " + ground_info.ToString() +
            "\nfly_info: " + fly_info.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
