//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.PsdkInterfaces
{
    [Serializable]
    public class PerceptionCameraParametersMsg : Message
    {
        public const string k_RosMessageName = "psdk_interfaces/PerceptionCameraParameters";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public byte stereo_cameras_direction;
        public double[] left_intrinsics;
        public double[] right_intrinsics;
        public double[] rotation_left_in_right;
        public double[] translation_left_in_right;

        public PerceptionCameraParametersMsg()
        {
            this.header = new Std.HeaderMsg();
            this.stereo_cameras_direction = 0;
            this.left_intrinsics = new double[9];
            this.right_intrinsics = new double[9];
            this.rotation_left_in_right = new double[9];
            this.translation_left_in_right = new double[3];
        }

        public PerceptionCameraParametersMsg(Std.HeaderMsg header, byte stereo_cameras_direction, double[] left_intrinsics, double[] right_intrinsics, double[] rotation_left_in_right, double[] translation_left_in_right)
        {
            this.header = header;
            this.stereo_cameras_direction = stereo_cameras_direction;
            this.left_intrinsics = left_intrinsics;
            this.right_intrinsics = right_intrinsics;
            this.rotation_left_in_right = rotation_left_in_right;
            this.translation_left_in_right = translation_left_in_right;
        }

        public static PerceptionCameraParametersMsg Deserialize(MessageDeserializer deserializer) => new PerceptionCameraParametersMsg(deserializer);

        private PerceptionCameraParametersMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.stereo_cameras_direction);
            deserializer.Read(out this.left_intrinsics, sizeof(double), 9);
            deserializer.Read(out this.right_intrinsics, sizeof(double), 9);
            deserializer.Read(out this.rotation_left_in_right, sizeof(double), 9);
            deserializer.Read(out this.translation_left_in_right, sizeof(double), 3);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.stereo_cameras_direction);
            serializer.Write(this.left_intrinsics);
            serializer.Write(this.right_intrinsics);
            serializer.Write(this.rotation_left_in_right);
            serializer.Write(this.translation_left_in_right);
        }

        public override string ToString()
        {
            return "PerceptionCameraParametersMsg: " +
            "\nheader: " + header.ToString() +
            "\nstereo_cameras_direction: " + stereo_cameras_direction.ToString() +
            "\nleft_intrinsics: " + System.String.Join(", ", left_intrinsics.ToList()) +
            "\nright_intrinsics: " + System.String.Join(", ", right_intrinsics.ToList()) +
            "\nrotation_left_in_right: " + System.String.Join(", ", rotation_left_in_right.ToList()) +
            "\ntranslation_left_in_right: " + System.String.Join(", ", translation_left_in_right.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
