//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.PsdkInterfaces
{
    [Serializable]
    public class PositionFusedMsg : Message
    {
        public const string k_RosMessageName = "psdk_interfaces/PositionFused";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public Geometry.PointMsg position;
        public byte x_health;
        public byte y_health;
        public byte z_health;

        public PositionFusedMsg()
        {
            this.header = new Std.HeaderMsg();
            this.position = new Geometry.PointMsg();
            this.x_health = 0;
            this.y_health = 0;
            this.z_health = 0;
        }

        public PositionFusedMsg(Std.HeaderMsg header, Geometry.PointMsg position, byte x_health, byte y_health, byte z_health)
        {
            this.header = header;
            this.position = position;
            this.x_health = x_health;
            this.y_health = y_health;
            this.z_health = z_health;
        }

        public static PositionFusedMsg Deserialize(MessageDeserializer deserializer) => new PositionFusedMsg(deserializer);

        private PositionFusedMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            this.position = Geometry.PointMsg.Deserialize(deserializer);
            deserializer.Read(out this.x_health);
            deserializer.Read(out this.y_health);
            deserializer.Read(out this.z_health);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.position);
            serializer.Write(this.x_health);
            serializer.Write(this.y_health);
            serializer.Write(this.z_health);
        }

        public override string ToString()
        {
            return "PositionFusedMsg: " +
            "\nheader: " + header.ToString() +
            "\nposition: " + position.ToString() +
            "\nx_health: " + x_health.ToString() +
            "\ny_health: " + y_health.ToString() +
            "\nz_health: " + z_health.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
