//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.PsdkInterfaces
{
    [Serializable]
    public class SubFileInfoMsg : Message
    {
        public const string k_RosMessageName = "psdk_interfaces/SubFileInfo";
        public override string RosMessageName => k_RosMessageName;

        public string name;
        public byte type;
        public uint size;
        public uint index;
        public long create_time_unix;
        public FileAttributesMsg attributes;

        public SubFileInfoMsg()
        {
            this.name = "";
            this.type = 0;
            this.size = 0;
            this.index = 0;
            this.create_time_unix = 0;
            this.attributes = new FileAttributesMsg();
        }

        public SubFileInfoMsg(string name, byte type, uint size, uint index, long create_time_unix, FileAttributesMsg attributes)
        {
            this.name = name;
            this.type = type;
            this.size = size;
            this.index = index;
            this.create_time_unix = create_time_unix;
            this.attributes = attributes;
        }

        public static SubFileInfoMsg Deserialize(MessageDeserializer deserializer) => new SubFileInfoMsg(deserializer);

        private SubFileInfoMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.name);
            deserializer.Read(out this.type);
            deserializer.Read(out this.size);
            deserializer.Read(out this.index);
            deserializer.Read(out this.create_time_unix);
            this.attributes = FileAttributesMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.name);
            serializer.Write(this.type);
            serializer.Write(this.size);
            serializer.Write(this.index);
            serializer.Write(this.create_time_unix);
            serializer.Write(this.attributes);
        }

        public override string ToString()
        {
            return "SubFileInfoMsg: " +
            "\nname: " + name.ToString() +
            "\ntype: " + type.ToString() +
            "\nsize: " + size.ToString() +
            "\nindex: " + index.ToString() +
            "\ncreate_time_unix: " + create_time_unix.ToString() +
            "\nattributes: " + attributes.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
