//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.PsdkInterfaces
{
    [Serializable]
    public class DisplayModeMsg : Message
    {
        public const string k_RosMessageName = "psdk_interfaces/DisplayMode";
        public override string RosMessageName => k_RosMessageName;

        public const byte DISPLAY_MODE_MANUAL_CTRL = 0;
        public const byte DISPLAY_MODE_ATTITUDE = 1;
        public const byte DISPLAY_MODE_RESERVED_2 = 2;
        public const byte DISPLAY_MODE_RESERVED_3 = 3;
        public const byte DISPLAY_MODE_RESERVED_4 = 4;
        public const byte DISPLAY_MODE_RESERVED_5 = 5;
        public const byte DISPLAY_MODE_P_GPS = 6;
        public const byte DISPLAY_MODE_RESERVED_7 = 7;
        public const byte DISPLAY_MODE_RESERVED_8 = 8;
        public const byte DISPLAY_MODE_HOTPOINT_MODE = 9;
        public const byte DISPLAY_MODE_ASSISTED_TAKEOFF = 10;
        public const byte DISPLAY_MODE_AUTO_TAKEOFF = 11;
        public const byte DISPLAY_MODE_AUTO_LANDING = 12;
        public const byte DISPLAY_MODE_RESERVED_13 = 13;
        public const byte DISPLAY_MODE_RESERVED_14 = 14;
        public const byte DISPLAY_MODE_NAVI_GO_HOME = 15;
        public const byte DISPLAY_MODE_RESERVED_16 = 16;
        public const byte DISPLAY_MODE_NAVI_SDK_CTRL = 17;
        public const byte DISPLAY_MODE_RESERVED_18 = 18;
        public const byte DISPLAY_MODE_RESERVED_19 = 19;
        public const byte DISPLAY_MODE_RESERVED_20 = 20;
        public const byte DISPLAY_MODE_RESERVED_21 = 21;
        public const byte DISPLAY_MODE_RESERVED_22 = 22;
        public const byte DISPLAY_MODE_RESERVED_23 = 23;
        public const byte DISPLAY_MODE_RESERVED_24 = 24;
        public const byte DISPLAY_MODE_RESERVED_25 = 25;
        public const byte DISPLAY_MODE_RESERVED_26 = 26;
        public const byte DISPLAY_MODE_RESERVED_27 = 27;
        public const byte DISPLAY_MODE_RESERVED_28 = 28;
        public const byte DISPLAY_MODE_RESERVED_29 = 29;
        public const byte DISPLAY_MODE_RESERVED_30 = 30;
        public const byte DISPLAY_MODE_RESERVED_31 = 31;
        public const byte DISPLAY_MODE_RESERVED_32 = 32;
        public const byte DISPLAY_MODE_FORCE_AUTO_LANDING = 33;
        public const byte DISPLAY_MODE_RESERVED_34 = 34;
        public const byte DISPLAY_MODE_RESERVED_35 = 35;
        public const byte DISPLAY_MODE_RESERVED_36 = 36;
        public const byte DISPLAY_MODE_RESERVED_37 = 37;
        public const byte DISPLAY_MODE_RESERVED_38 = 38;
        public const byte DISPLAY_MODE_RESERVED_39 = 39;
        public const byte DISPLAY_MODE_SEARCH_MODE = 40;
        public const byte DISPLAY_MODE_ENGINE_START = 41;
        public const byte DISPLAY_MODE_RESERVED_42 = 42;
        public const byte DISPLAY_MODE_RESERVED_43 = 42;
        public Std.HeaderMsg header;
        public byte display_mode;

        public DisplayModeMsg()
        {
            this.header = new Std.HeaderMsg();
            this.display_mode = 0;
        }

        public DisplayModeMsg(Std.HeaderMsg header, byte display_mode)
        {
            this.header = header;
            this.display_mode = display_mode;
        }

        public static DisplayModeMsg Deserialize(MessageDeserializer deserializer) => new DisplayModeMsg(deserializer);

        private DisplayModeMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.display_mode);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.display_mode);
        }

        public override string ToString()
        {
            return "DisplayModeMsg: " +
            "\nheader: " + header.ToString() +
            "\ndisplay_mode: " + display_mode.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
