//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.PsdkInterfaces
{
    [Serializable]
    public class HomePositionMsg : Message
    {
        public const string k_RosMessageName = "psdk_interfaces/HomePosition";
        public override string RosMessageName => k_RosMessageName;

        public const byte HOME_POSITION_STATUS_FAILED = 0;
        public const byte HOME_POSITION_STATUS_SUCCESS = 1;
        public Std.HeaderMsg header;
        public byte home_position_status;
        public double latitude;
        public double longitude;

        public HomePositionMsg()
        {
            this.header = new Std.HeaderMsg();
            this.home_position_status = 0;
            this.latitude = 0.0;
            this.longitude = 0.0;
        }

        public HomePositionMsg(Std.HeaderMsg header, byte home_position_status, double latitude, double longitude)
        {
            this.header = header;
            this.home_position_status = home_position_status;
            this.latitude = latitude;
            this.longitude = longitude;
        }

        public static HomePositionMsg Deserialize(MessageDeserializer deserializer) => new HomePositionMsg(deserializer);

        private HomePositionMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.home_position_status);
            deserializer.Read(out this.latitude);
            deserializer.Read(out this.longitude);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.home_position_status);
            serializer.Write(this.latitude);
            serializer.Write(this.longitude);
        }

        public override string ToString()
        {
            return "HomePositionMsg: " +
            "\nheader: " + header.ToString() +
            "\nhome_position_status: " + home_position_status.ToString() +
            "\nlatitude: " + latitude.ToString() +
            "\nlongitude: " + longitude.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
